// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Njs.Core.Infrastructure.Persistence;

#nullable disable

namespace Njs.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NjsContext))]
    [Migration("20230106232006_AddStoreProductCategorySeed")]
    partial class AddStoreProductCategorySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("Njs.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nihil enim at autem pariatur dolores.",
                            LogoUrl = "https://picsum.photos/640/480/?image=572",
                            Name = "Baby"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Animi voluptate est libero dignissimos sunt qui totam quae.",
                            LogoUrl = "https://picsum.photos/640/480/?image=634",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Et magnam magnam libero praesentium voluptatem sed sunt id fugiat.",
                            LogoUrl = "https://picsum.photos/640/480/?image=238",
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Excepturi molestiae quae veritatis deleniti minus est.",
                            LogoUrl = "https://picsum.photos/640/480/?image=813",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Illum reiciendis rerum quasi.",
                            LogoUrl = "https://picsum.photos/640/480/?image=374",
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Quo sint sit commodi tenetur accusantium placeat sunt.",
                            LogoUrl = "https://picsum.photos/640/480/?image=904",
                            Name = "Baby"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Rerum aliquam est sapiente ut sunt ut omnis maiores.",
                            LogoUrl = "https://picsum.photos/640/480/?image=1019",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Aut quia sed iste exercitationem enim omnis.",
                            LogoUrl = "https://picsum.photos/640/480/?image=233",
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ut molestiae quos sint iure.",
                            LogoUrl = "https://picsum.photos/640/480/?image=769",
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Nesciunt eum ipsam quo culpa officia quae.",
                            LogoUrl = "https://picsum.photos/640/480/?image=1058",
                            Name = "Tools"
                        });
                });

            modelBuilder.Entity("Njs.Core.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Formatting")
                        .HasColumnType("int");

                    b.Property<string>("GroupSeparator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EUR",
                            DecimalPlaces = 2,
                            DecimalSeparator = ".",
                            Formatting = 0,
                            GroupSeparator = ",",
                            Sign = "€"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ISK",
                            DecimalPlaces = 0,
                            DecimalSeparator = ",",
                            Formatting = 3,
                            GroupSeparator = ".",
                            Sign = "kr."
                        });
                });

            modelBuilder.Entity("Njs.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Njs.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(2)
                        .HasColumnType("decimal(2,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Njs.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Unbranded Cotton Car"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Awesome Granite Pizza"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 1,
                            Title = "Sleek Steel Car"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Refined Fresh Salad"
                        },
                        new
                        {
                            Id = 5,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Small Metal Keyboard"
                        },
                        new
                        {
                            Id = 7,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Licensed Granite Pizza"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Awesome Granite Bike"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 2,
                            Title = "Sleek Cotton Shoes"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Fantastic Wooden Computer"
                        },
                        new
                        {
                            Id = 11,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Handmade Soft Bacon"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 1,
                            Title = "Practical Metal Computer"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Refined Concrete Shirt"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Gorgeous Granite Car"
                        },
                        new
                        {
                            Id = 15,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Tasty Soft Bacon"
                        },
                        new
                        {
                            Id = 16,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Practical Cotton Pants"
                        },
                        new
                        {
                            Id = 17,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Incredible Granite Towels"
                        },
                        new
                        {
                            Id = 18,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 1,
                            Title = "Fantastic Wooden Table"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Intelligent Cotton Hat"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Generic Rubber Sausages"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 1,
                            Title = "Gorgeous Granite Ball"
                        },
                        new
                        {
                            Id = 22,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Fantastic Plastic Mouse"
                        },
                        new
                        {
                            Id = 23,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Incredible Plastic Pizza"
                        },
                        new
                        {
                            Id = 24,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 1,
                            Title = "Generic Cotton Pants"
                        },
                        new
                        {
                            Id = 25,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 1,
                            Title = "Rustic Granite Car"
                        },
                        new
                        {
                            Id = 26,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 1,
                            Title = "Handcrafted Plastic Sausages"
                        },
                        new
                        {
                            Id = 27,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Fantastic Plastic Shirt"
                        },
                        new
                        {
                            Id = 28,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Licensed Frozen Pizza"
                        },
                        new
                        {
                            Id = 29,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Ergonomic Granite Chair"
                        },
                        new
                        {
                            Id = 30,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Intelligent Frozen Gloves"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 1,
                            Title = "Gorgeous Soft Keyboard"
                        },
                        new
                        {
                            Id = 32,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Intelligent Plastic Fish"
                        },
                        new
                        {
                            Id = 33,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Generic Concrete Tuna"
                        },
                        new
                        {
                            Id = 34,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 2,
                            Title = "Generic Wooden Chicken"
                        },
                        new
                        {
                            Id = 35,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Gorgeous Fresh Bacon"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Awesome Fresh Towels"
                        },
                        new
                        {
                            Id = 37,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Handmade Rubber Soap"
                        },
                        new
                        {
                            Id = 38,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 1,
                            Title = "Unbranded Fresh Sausages"
                        },
                        new
                        {
                            Id = 39,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Incredible Soft Ball"
                        },
                        new
                        {
                            Id = 40,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Generic Metal Bike"
                        },
                        new
                        {
                            Id = 41,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Handcrafted Granite Sausages"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Intelligent Rubber Keyboard"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Fantastic Metal Shoes"
                        },
                        new
                        {
                            Id = 44,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Gorgeous Cotton Bike"
                        },
                        new
                        {
                            Id = 45,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Intelligent Frozen Gloves"
                        },
                        new
                        {
                            Id = 46,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 1,
                            Title = "Fantastic Wooden Hat"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 1,
                            Title = "Tasty Rubber Table"
                        },
                        new
                        {
                            Id = 48,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Unbranded Soft Table"
                        },
                        new
                        {
                            Id = 49,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Small Metal Pants"
                        },
                        new
                        {
                            Id = 50,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Handcrafted Concrete Car"
                        },
                        new
                        {
                            Id = 51,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Fantastic Metal Bike"
                        },
                        new
                        {
                            Id = 52,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Fantastic Frozen Shoes"
                        },
                        new
                        {
                            Id = 53,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Ergonomic Granite Bacon"
                        },
                        new
                        {
                            Id = 54,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Fantastic Frozen Shoes"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Handmade Frozen Fish"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 2,
                            Title = "Awesome Rubber Chips"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Rustic Plastic Towels"
                        },
                        new
                        {
                            Id = 58,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 1,
                            Title = "Unbranded Metal Salad"
                        },
                        new
                        {
                            Id = 59,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Sleek Plastic Cheese"
                        },
                        new
                        {
                            Id = 60,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Awesome Fresh Table"
                        },
                        new
                        {
                            Id = 61,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Handmade Concrete Bike"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 1,
                            Title = "Practical Frozen Sausages"
                        },
                        new
                        {
                            Id = 63,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Sleek Concrete Hat"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Practical Fresh Sausages"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Licensed Soft Tuna"
                        },
                        new
                        {
                            Id = 66,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Refined Granite Fish"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 1,
                            Title = "Tasty Granite Car"
                        },
                        new
                        {
                            Id = 68,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Practical Cotton Computer"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Awesome Fresh Soap"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 1,
                            Title = "Rustic Wooden Salad"
                        },
                        new
                        {
                            Id = 71,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Tasty Plastic Car"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Sleek Cotton Pants"
                        },
                        new
                        {
                            Id = 73,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 1,
                            Title = "Ergonomic Metal Fish"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Handmade Frozen Chips"
                        },
                        new
                        {
                            Id = 75,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Unbranded Wooden Hat"
                        },
                        new
                        {
                            Id = 76,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Unbranded Cotton Fish"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Sleek Concrete Tuna"
                        },
                        new
                        {
                            Id = 78,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 1,
                            Title = "Small Soft Car"
                        },
                        new
                        {
                            Id = 79,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Sleek Wooden Chair"
                        },
                        new
                        {
                            Id = 80,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Handmade Wooden Cheese"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Sleek Cotton Shoes"
                        },
                        new
                        {
                            Id = 82,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Handmade Frozen Shoes"
                        },
                        new
                        {
                            Id = 83,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Ergonomic Frozen Gloves"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 1,
                            Title = "Tasty Granite Chips"
                        });
                });

            modelBuilder.Entity("Njs.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Njs.Core.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "HR",
                            CurrencyId = 1,
                            DisplayName = "Croatia",
                            TenantId = ".1"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "IS",
                            CurrencyId = 2,
                            DisplayName = "Iceland",
                            TenantId = ".2"
                        });
                });

            modelBuilder.Entity("Njs.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "+385",
                            Email = "admin@tvz.hr",
                            HashedPassword = "AQAAAAIAAYagAAAAEDMkxkZkRHtpx9JDKSK/5jJWy9d2aODDEZ5S81hBZxM4au5NfpP8RRH2AqCrQM5DAA==",
                            LocalPhoneNumber = "xx yyyy zzz",
                            Username = "Administrator"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Njs.Core.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Njs.Core.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Njs.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Njs.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Njs.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Njs.Core.Entities.Product", b =>
                {
                    b.HasOne("Njs.Core.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Njs.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Njs.Core.Entities.User", "Owner")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Njs.Core.Entities.Store", b =>
                {
                    b.HasOne("Njs.Core.Entities.Currency", "Currency")
                        .WithMany("Stores")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Njs.Core.Entities.Currency", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Njs.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Njs.Core.Entities.Store", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Njs.Core.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
