// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Njs.Core.Infrastructure.Persistence;

#nullable disable

namespace Njs.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NjsContext))]
    partial class NjsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("Njs.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Delectus ipsum quo nemo porro ex.",
                            LogoUrl = "https://picsum.photos/640/480/?image=937",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sed neque et voluptatem.",
                            LogoUrl = "https://picsum.photos/640/480/?image=1059",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ut et ut labore facilis.",
                            LogoUrl = "https://picsum.photos/640/480/?image=1072",
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Qui error sed dolor voluptatem quam.",
                            LogoUrl = "https://picsum.photos/640/480/?image=619",
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Molestias tempora eligendi voluptatem necessitatibus unde dolore nihil.",
                            LogoUrl = "https://picsum.photos/640/480/?image=1023",
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ut est id quasi vero rerum eius sit qui.",
                            LogoUrl = "https://picsum.photos/640/480/?image=956",
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Officiis expedita autem dolorem voluptatem molestiae expedita et blanditiis aut.",
                            LogoUrl = "https://picsum.photos/640/480/?image=736",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Vel cum rerum dolores molestiae magnam quam.",
                            LogoUrl = "https://picsum.photos/640/480/?image=701",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Consectetur et consequuntur delectus quam.",
                            LogoUrl = "https://picsum.photos/640/480/?image=696",
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Doloremque deleniti eos et minus.",
                            LogoUrl = "https://picsum.photos/640/480/?image=797",
                            Name = "Games"
                        });
                });

            modelBuilder.Entity("Njs.Core.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Formatting")
                        .HasColumnType("int");

                    b.Property<string>("GroupSeparator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EUR",
                            DecimalPlaces = 2,
                            DecimalSeparator = ".",
                            Formatting = 0,
                            GroupSeparator = ",",
                            Sign = "€"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ISK",
                            DecimalPlaces = 0,
                            DecimalSeparator = ",",
                            Formatting = 3,
                            GroupSeparator = ".",
                            Sign = "kr."
                        });
                });

            modelBuilder.Entity("Njs.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Njs.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(2)
                        .HasColumnType("decimal(2,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Njs.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 115,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Handcrafted Frozen Towels"
                        },
                        new
                        {
                            Id = 116,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Incredible Plastic Shirt"
                        },
                        new
                        {
                            Id = 117,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 1,
                            Title = "Awesome Soft Shirt"
                        },
                        new
                        {
                            Id = 118,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Handcrafted Soft Salad"
                        },
                        new
                        {
                            Id = 119,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Incredible Metal Car"
                        },
                        new
                        {
                            Id = 120,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Gorgeous Metal Shoes"
                        },
                        new
                        {
                            Id = 121,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Handmade Fresh Pizza"
                        },
                        new
                        {
                            Id = 122,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Tasty Frozen Tuna"
                        },
                        new
                        {
                            Id = 123,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 1,
                            Title = "Generic Fresh Soap"
                        },
                        new
                        {
                            Id = 124,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Intelligent Soft Salad"
                        },
                        new
                        {
                            Id = 125,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Refined Cotton Hat"
                        },
                        new
                        {
                            Id = 126,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 1,
                            Title = "Handmade Soft Hat"
                        },
                        new
                        {
                            Id = 127,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Small Concrete Fish"
                        },
                        new
                        {
                            Id = 128,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Small Plastic Chair"
                        },
                        new
                        {
                            Id = 129,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 2,
                            Title = "Refined Soft Sausages"
                        },
                        new
                        {
                            Id = 130,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Refined Plastic Pants"
                        },
                        new
                        {
                            Id = 131,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Incredible Frozen Tuna"
                        },
                        new
                        {
                            Id = 132,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Small Rubber Pants"
                        },
                        new
                        {
                            Id = 133,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Ergonomic Cotton Tuna"
                        },
                        new
                        {
                            Id = 134,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Refined Cotton Mouse"
                        },
                        new
                        {
                            Id = 135,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Tasty Metal Bacon"
                        },
                        new
                        {
                            Id = 136,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Handmade Metal Mouse"
                        },
                        new
                        {
                            Id = 137,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Licensed Steel Computer"
                        },
                        new
                        {
                            Id = 138,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Ergonomic Cotton Computer"
                        },
                        new
                        {
                            Id = 139,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Handcrafted Granite Shirt"
                        },
                        new
                        {
                            Id = 140,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Rustic Rubber Gloves"
                        },
                        new
                        {
                            Id = 141,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Sleek Plastic Chicken"
                        },
                        new
                        {
                            Id = 142,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Unbranded Metal Pizza"
                        },
                        new
                        {
                            Id = 143,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Tasty Concrete Mouse"
                        },
                        new
                        {
                            Id = 144,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 1,
                            Title = "Small Cotton Bacon"
                        },
                        new
                        {
                            Id = 145,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Handmade Granite Car"
                        },
                        new
                        {
                            Id = 146,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Handcrafted Plastic Shoes"
                        },
                        new
                        {
                            Id = 147,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Licensed Cotton Hat"
                        },
                        new
                        {
                            Id = 148,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Fantastic Frozen Bacon"
                        },
                        new
                        {
                            Id = 149,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Licensed Steel Pants"
                        },
                        new
                        {
                            Id = 150,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Generic Frozen Pants"
                        },
                        new
                        {
                            Id = 151,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Unbranded Frozen Shirt"
                        },
                        new
                        {
                            Id = 152,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Generic Granite Gloves"
                        },
                        new
                        {
                            Id = 153,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 2,
                            Title = "Sleek Granite Bacon"
                        },
                        new
                        {
                            Id = 154,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Sleek Plastic Fish"
                        },
                        new
                        {
                            Id = 155,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 1,
                            Title = "Licensed Rubber Table"
                        },
                        new
                        {
                            Id = 156,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Tasty Plastic Chair"
                        },
                        new
                        {
                            Id = 157,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 2,
                            Title = "Licensed Frozen Bike"
                        },
                        new
                        {
                            Id = 158,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 1,
                            Title = "Fantastic Soft Cheese"
                        },
                        new
                        {
                            Id = 159,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Practical Wooden Sausages"
                        },
                        new
                        {
                            Id = 160,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 1,
                            Title = "Incredible Rubber Pants"
                        },
                        new
                        {
                            Id = 161,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Generic Frozen Hat"
                        },
                        new
                        {
                            Id = 162,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 1,
                            Title = "Intelligent Metal Cheese"
                        },
                        new
                        {
                            Id = 163,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Refined Frozen Soap"
                        },
                        new
                        {
                            Id = 164,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Incredible Rubber Salad"
                        },
                        new
                        {
                            Id = 165,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Handmade Plastic Mouse"
                        },
                        new
                        {
                            Id = 166,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 1,
                            Title = "Practical Granite Fish"
                        },
                        new
                        {
                            Id = 167,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Gorgeous Fresh Cheese"
                        },
                        new
                        {
                            Id = 168,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Rustic Cotton Chips"
                        },
                        new
                        {
                            Id = 169,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Sleek Rubber Chips"
                        },
                        new
                        {
                            Id = 170,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 1,
                            Title = "Intelligent Rubber Ball"
                        },
                        new
                        {
                            Id = 171,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Incredible Wooden Tuna"
                        },
                        new
                        {
                            Id = 172,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 1,
                            Title = "Tasty Rubber Pants"
                        },
                        new
                        {
                            Id = 173,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Unbranded Wooden Chicken"
                        },
                        new
                        {
                            Id = 174,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 1,
                            Title = "Handcrafted Metal Chair"
                        },
                        new
                        {
                            Id = 175,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Practical Metal Pizza"
                        },
                        new
                        {
                            Id = 176,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Tasty Fresh Towels"
                        },
                        new
                        {
                            Id = 177,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Awesome Cotton Pizza"
                        },
                        new
                        {
                            Id = 178,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 1,
                            Title = "Sleek Fresh Sausages"
                        },
                        new
                        {
                            Id = 179,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 1,
                            Title = "Intelligent Fresh Hat"
                        },
                        new
                        {
                            Id = 180,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Ergonomic Cotton Pizza"
                        },
                        new
                        {
                            Id = 181,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 1,
                            Title = "Practical Steel Fish"
                        },
                        new
                        {
                            Id = 182,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Handcrafted Plastic Fish"
                        },
                        new
                        {
                            Id = 183,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Tasty Wooden Pants"
                        },
                        new
                        {
                            Id = 184,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Practical Wooden Tuna"
                        },
                        new
                        {
                            Id = 185,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Tasty Cotton Table"
                        },
                        new
                        {
                            Id = 186,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 1,
                            Title = "Rustic Fresh Soap"
                        },
                        new
                        {
                            Id = 187,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 1,
                            Title = "Rustic Soft Soap"
                        },
                        new
                        {
                            Id = 188,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Fantastic Cotton Soap"
                        },
                        new
                        {
                            Id = 189,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Tasty Steel Salad"
                        },
                        new
                        {
                            Id = 190,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Unbranded Metal Ball"
                        },
                        new
                        {
                            Id = 191,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Sleek Wooden Soap"
                        },
                        new
                        {
                            Id = 192,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 1,
                            Title = "Fantastic Wooden Salad"
                        },
                        new
                        {
                            Id = 193,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Unbranded Fresh Bike"
                        },
                        new
                        {
                            Id = 194,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 1,
                            Title = "Incredible Metal Computer"
                        },
                        new
                        {
                            Id = 195,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Practical Soft Salad"
                        },
                        new
                        {
                            Id = 196,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Practical Metal Salad"
                        },
                        new
                        {
                            Id = 197,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Gorgeous Metal Soap"
                        },
                        new
                        {
                            Id = 198,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 1,
                            Title = "Licensed Fresh Sausages"
                        },
                        new
                        {
                            Id = 199,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 2,
                            Title = "Licensed Wooden Pizza"
                        },
                        new
                        {
                            Id = 200,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Rustic Frozen Shirt"
                        },
                        new
                        {
                            Id = 201,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Rustic Steel Chips"
                        },
                        new
                        {
                            Id = 202,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Small Soft Computer"
                        },
                        new
                        {
                            Id = 203,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Tasty Frozen Shirt"
                        },
                        new
                        {
                            Id = 204,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Rustic Fresh Chips"
                        },
                        new
                        {
                            Id = 205,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Gorgeous Cotton Gloves"
                        },
                        new
                        {
                            Id = 206,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Small Frozen Bike"
                        },
                        new
                        {
                            Id = 207,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Handcrafted Cotton Chips"
                        },
                        new
                        {
                            Id = 208,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Intelligent Rubber Car"
                        },
                        new
                        {
                            Id = 209,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 2,
                            Title = "Tasty Fresh Car"
                        },
                        new
                        {
                            Id = 210,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Licensed Metal Cheese"
                        },
                        new
                        {
                            Id = 211,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 1,
                            Title = "Gorgeous Plastic Towels"
                        },
                        new
                        {
                            Id = 212,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 1,
                            Title = "Handcrafted Fresh Chips"
                        },
                        new
                        {
                            Id = 213,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Fantastic Fresh Hat"
                        },
                        new
                        {
                            Id = 214,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Generic Rubber Salad"
                        },
                        new
                        {
                            Id = 215,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Handmade Fresh Ball"
                        },
                        new
                        {
                            Id = 216,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Sleek Rubber Mouse"
                        },
                        new
                        {
                            Id = 217,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Gorgeous Wooden Towels"
                        },
                        new
                        {
                            Id = 218,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Rustic Steel Pants"
                        },
                        new
                        {
                            Id = 219,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 1,
                            Title = "Awesome Metal Salad"
                        },
                        new
                        {
                            Id = 220,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Unbranded Cotton Pizza"
                        },
                        new
                        {
                            Id = 221,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 2,
                            Title = "Unbranded Plastic Cheese"
                        },
                        new
                        {
                            Id = 222,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 2,
                            Title = "Handmade Steel Salad"
                        },
                        new
                        {
                            Id = 223,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Tasty Rubber Mouse"
                        },
                        new
                        {
                            Id = 224,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            StoreId = 2,
                            Title = "Gorgeous Steel Bike"
                        },
                        new
                        {
                            Id = 225,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 2,
                            Title = "Unbranded Cotton Chicken"
                        },
                        new
                        {
                            Id = 226,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 1,
                            Title = "Practical Concrete Hat"
                        },
                        new
                        {
                            Id = 227,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Unbranded Concrete Chips"
                        },
                        new
                        {
                            Id = 228,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Awesome Fresh Bike"
                        },
                        new
                        {
                            Id = 229,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Unbranded Cotton Chips"
                        },
                        new
                        {
                            Id = 230,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Intelligent Granite Pants"
                        },
                        new
                        {
                            Id = 231,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 1,
                            Title = "Handmade Wooden Pants"
                        },
                        new
                        {
                            Id = 232,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Small Concrete Chair"
                        },
                        new
                        {
                            Id = 233,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Licensed Concrete Salad"
                        },
                        new
                        {
                            Id = 234,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 1,
                            Title = "Licensed Concrete Sausages"
                        },
                        new
                        {
                            Id = 235,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Incredible Cotton Salad"
                        },
                        new
                        {
                            Id = 236,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 2,
                            Title = "Awesome Plastic Pizza"
                        },
                        new
                        {
                            Id = 237,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 2,
                            Title = "Refined Fresh Bacon"
                        },
                        new
                        {
                            Id = 238,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 2,
                            Title = "Ergonomic Granite Gloves"
                        },
                        new
                        {
                            Id = 239,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Intelligent Cotton Tuna"
                        },
                        new
                        {
                            Id = 240,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Handmade Steel Shoes"
                        },
                        new
                        {
                            Id = 241,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            StoreId = 1,
                            Title = "Ergonomic Steel Mouse"
                        },
                        new
                        {
                            Id = 242,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Sleek Cotton Soap"
                        },
                        new
                        {
                            Id = 243,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Tasty Frozen Bacon"
                        },
                        new
                        {
                            Id = 244,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Sleek Rubber Hat"
                        },
                        new
                        {
                            Id = 245,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 2,
                            Title = "Refined Concrete Keyboard"
                        },
                        new
                        {
                            Id = 246,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            StoreId = 2,
                            Title = "Fantastic Rubber Pants"
                        },
                        new
                        {
                            Id = 247,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 1,
                            Title = "Practical Concrete Soap"
                        },
                        new
                        {
                            Id = 248,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            StoreId = 2,
                            Title = "Generic Metal Table"
                        },
                        new
                        {
                            Id = 249,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Rustic Plastic Bacon"
                        },
                        new
                        {
                            Id = 250,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            StoreId = 2,
                            Title = "Incredible Granite Mouse"
                        },
                        new
                        {
                            Id = 251,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Gorgeous Rubber Salad"
                        },
                        new
                        {
                            Id = 252,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Intelligent Rubber Sausages"
                        },
                        new
                        {
                            Id = 253,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            StoreId = 1,
                            Title = "Handcrafted Fresh Salad"
                        },
                        new
                        {
                            Id = 254,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Handcrafted Steel Bike"
                        },
                        new
                        {
                            Id = 255,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 1,
                            Title = "Incredible Steel Mouse"
                        },
                        new
                        {
                            Id = 256,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 2,
                            Title = "Refined Cotton Pants"
                        },
                        new
                        {
                            Id = 257,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            StoreId = 2,
                            Title = "Handmade Wooden Bacon"
                        },
                        new
                        {
                            Id = 258,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            StoreId = 1,
                            Title = "Awesome Soft Computer"
                        },
                        new
                        {
                            Id = 259,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            StoreId = 2,
                            Title = "Generic Concrete Car"
                        },
                        new
                        {
                            Id = 260,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Gorgeous Steel Table"
                        },
                        new
                        {
                            Id = 261,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            StoreId = 2,
                            Title = "Licensed Frozen Shirt"
                        },
                        new
                        {
                            Id = 262,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            StoreId = 1,
                            Title = "Incredible Concrete Soap"
                        },
                        new
                        {
                            Id = 263,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            StoreId = 2,
                            Title = "Handmade Frozen Table"
                        });
                });

            modelBuilder.Entity("Njs.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Njs.Core.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "HR",
                            CurrencyId = 1,
                            DisplayName = "Croatia",
                            TenantId = ".1"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "IS",
                            CurrencyId = 2,
                            DisplayName = "Iceland",
                            TenantId = ".2"
                        });
                });

            modelBuilder.Entity("Njs.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "+385",
                            Email = "admin@tvz.hr",
                            HashedPassword = "AQAAAAIAAYagAAAAEMBj15cQ4VQFVbAli2IMlJqo0FeYMrTYp/j39BLBstxwUKzVccoyhfn9EfJTYpr/ng==",
                            LocalPhoneNumber = "xx yyyy zzz",
                            Username = "Administrator"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Njs.Core.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Njs.Core.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Njs.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Njs.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Njs.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Njs.Core.Entities.Product", b =>
                {
                    b.HasOne("Njs.Core.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Njs.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Njs.Core.Entities.User", "Owner")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Njs.Core.Entities.Store", b =>
                {
                    b.HasOne("Njs.Core.Entities.Currency", "Currency")
                        .WithMany("Stores")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Njs.Core.Entities.Currency", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Njs.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Njs.Core.Entities.Store", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Njs.Core.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
